[env:pico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower

; Enable WiFi and Bluetooth
build_flags = 
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_WIFI

; Filesystem for storing WiFi credentials (256KB)
board_build.filesystem_size = 256k

lib_deps = 
    moononournation/GFX Library for Arduino@^1.5.8

monitor_speed = 115200
